title: Into the glitch
description: on digital forensics and malware analysis
show_downloads: false
markdown: GFM
url: "yaps8.github.io"
google_analytics:
theme: jekyll-theme-cayman
plugins:
  - jekyll-seo-tag
